"""add timezone

Revision ID: 3e0892a4fffb
Revises: 2d8b59070772
Create Date: 2026-05-22 12:01:02.274203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0892a4fffb'
down_revision: Union[str, None] = '2d8b59070772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_settings', sa.Column('time_zone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_settings', 'time_zone')
    # ### end Alembic commands ###
